name: Publish to PyPI.org
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build cibuildwheel
          
      # Build wheels for all platforms
      - name: Build Linux wheels
        run: cibuildwheel --output-dir dist --platform linux
        env:
          CIBW_SKIP: "pp* *musllinux*"
          
      - name: Build Windows wheels
        run: cibuildwheel --output-dir dist --platform windows
        env:
          CIBW_SKIP: "pp*"
          
      - name: Build macOS wheels
        run: cibuildwheel --output-dir dist --platform macos
        env:
          CIBW_SKIP: "pp*"
          
      - name: Build sdist
        run: python -m build --sdist --outdir dist
        
      - name: List built packages
        run: ls -la dist/
        
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
